Changelog
=========

Version 1.3.1
-------------

- Fix bug related to doble inclusion of DEFAULT_EXTENSIONS.
- Remove the extra django filters extension and document the change.


Version 1.3.0
-------------

- Now all builtin filters, and global functions are implemented
  using jinja2 extensions.
- Breaking change: JINJA2_FILTERS_REPLACE_FROM_DJANGO is removed


Version 1.2.1
-------------

- Improved JINJA2_LOADER handling for django <= 1.7
- Add documentation entry for JINJA2_LOADER.


Version 1.2.0
-------------

- Allow set custom module as translation engine. (by @toshka)


Version 1.1.1
-------------

- Fix typos on function names.
- Honor Django's `setting_changed` signal to reinitialize the Jinja2 environment.

Thanks to @akx



Version 1.1.0
-------------

- Code base refactored.
- Add django 1.8 support.
- Remove `fix_ampersands` filter.
- Fix linebreaksbr autoescape bug.
- Start using `jinja2.DebugUndefined` when settings.DEBUG is True.


Version 1.0.5
-------------

- Fix template loaders order.
- Convert documentation to asciidoctor.
- Move changelog to separated file.


Version 1.0.4
-------------

- Add render_with decorator as replacement for django inclusion_tag.
- Reorder how builtin functions/filters are setted making easy overwrite them.

Version 1.0.3
-------------

- Add timezone template filters and template global functions: localtime, tz and timezone.

Version 1.0.2
-------------

- Fix bug with application loading with django < 1.7

Version 1.0.1
-------------

- Fix bug introduced in previous version on `easy_thumbnails` contrib app.

Version 1.0.0
-------------

- Major code cleanup.
- Full django 1.7+ support
- Add JINJA2_CONSTANTS settings.

Version 0.25
------------

- Enable newstyle gettext by default.
- Add settings for easy disable newstyle gettext.


Version 0.24
------------

- Fix django 1.7 warnings on run tests.
- Add all rest methods to error views (403, 404, 500).

Version 0.23
------------

- Add settings JINJA2_FILTERS_REPLACE_FROM_DJANGO
- Add settings JINJA2_MUTE_URLRESOLVE_EXCEPTIONS
- Improvements on cache tag.
- Other bugfixes.


Version 0.22
------------

- Change template order selection.
- New contrib: subdomains
- New contrib: dajax-ice
- Documentation fixes.
- Minor improvements.

Version 0.21
------------

- Remove obsolete __version__ variable from __init__.py file.
- Add bytecode cache with django cache framework support.

Version 0.20
------------

- Introduce backward incompatible change: all contrib apps
  are renamed (prepened _ on each module name) for avoid
  name conflicts with the original package.

Version 0.19
------------

- Bugfixes related to autoescape.

Version 0.18
------------

- Test singnal when stream template method is used.

Version 0.17
------------

- Add 4xx/500 django special views.

Version 0.16
------------

- Remove distribute dependency.

Version 0.15
------------

- Put autoescape ON by default.
- Add easy_thumbnails contrib app
- Add django humanize contrib app

Version 0.14
------------

- Add jinja2 extensions loading by default

Version 0.13
------------

- New intercept method by regex is added.
- Documentation improvements.
