= django-jinja - Jinja2 Template Engine for Django
Andrey Antukh, <niwi@niwi.be>
1.3.2
:toc: left
:numbered:
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:


== Introduction

django-jinja is a xref:license[BSD Licensed], simple and nonobstructive jinja2 integration with Django.

Jinja2 provides certain advantages over the native system of Django, for example, explicit calls to
callable from templates, has better performance and has a plugin system, etc ...

There are other projects that attempt do same thing: Djinja, Coffin, etc... Why one more?

- Unlike Djinja, **django-jinja** is not intended to replace a Django template engine, but rather,
  it complements the Django's template engine, giving the possibility to use both.
- Unlike Coffin, the django-jinja codebase is much smaller and more modern. This way is much more
  maintainable and easily understandable how the library works.


=== Features

- Auto-load templatetags compatible with Jinja2 on same way as Django.
- Django templates can coexist with Jinja2 templates without any problems.
  It works as middleware, intercepts Jinja templates by file path pattern.
- Django template filters and tags can mostly be used in Jinja2 templates.
- I18n subsystem adapted for Jinja2 (makemessages now collects messages from Jinja templates)
- Compatible with python2 and python3 using same codebase.
- jinja2 bytecode cache adapted for use django cache subsystem.
- Django 1.8 support out of the box.

== Requirements

- Python 2.7, 3.3 or 3.4
- Django 1.5, 1.6, 1.7 and 1.8
- jinja2 >= 2.7.0


=== Installation

The simplest way to install **django-jinja** is using **pip**:

[source, bash]
----
pip install django-jinja
----

Add add it to django installed apps list:

[source, python]
----
INSTALLED_APPS += ('django_jinja',)
----

== User guide (django +++<=+++ 1.7)

=== Introduction

Since django-jinja supports two ways to setup (mainly for django <= 1.7 and django >= 1.8)
this section tries expain how to setup it for django <= 1.7.


=== Quick Setup

The first step for configure _django-jinja_ is replace default
django template loaders:

[source, python]
----
TEMPLATE_LOADERS = (
    'django_jinja.loaders.FileSystemLoader',
    'django_jinja.loaders.AppLoader',
)
----

django-jinja template loaders inherit's from a django template loaders and works like middleware,
intercepts by predefined condition templates for render with jinja2 engine.

The simplest condition is using file extensions:

[source, python]
----
DEFAULT_JINJA2_TEMPLATE_EXTENSION = '.jinja'
----

With this settings, django-jinja intercepts all templates with `.jinja` extension and render them with
jinja2 engine and templates that not matches the `.jinja` extension are forwarded to django templates
engine.


=== Advances settings

==== Regex based template matching

Additionaly, *django-jinja* exposes, more advanced matcher, using regular exceptions:

[source, python]
----
# Same behavior of default intercept method
# by extension but using regex (not recommended)
DEFAULT_JINJA2_TEMPLATE_INTERCEPT_RE = r'.*jinja$'

# More advanced method. Intercept all templates
# except from django admin.
DEFAULT_JINJA2_TEMPLATE_INTERCEPT_RE = r"^(?!admin/).*"
----


==== Setup autoescape

You can enable or disable autoescaping with `JINJA2_AUTOESCAPE` setting.

[source, python]
----
# Enable/Disable autoescaping (default: True)
JINJA2_AUTOESCAPE = True
----


==== Mute url resolve exceptions

Sometimes, you want simply mute exceptions related to url resolving. You can mute exceptions
with the following entry on your settings:

[source, python]
----
# Mute reverse url exceptions (default: False)
JINJA2_MUTE_URLRESOLVE_EXCEPTIONS = True
----


==== Set custom loader

django-jinja by default setups a proper template loader for load templates from
django's `TEMPLATES_DIRS` and app specific templates. But in some circumstances you
want override completely it. This can be done using the following entry on
your settings:

[source, python]
----
# Set custom loader
import jinja2
JINJA2_LOADER = jinja2.FileSystemLoader(["/some/path"])
----

==== Add additional extensions

django-jinja, by default set up a great amount of extensions for make your experience
using jinja in django painless. But if you want add more extesions, you can done
using `JINJA2_EXTENSIONS`:

[source, python]
----
JINJA2_EXTENSIONS = [
    # The default extensions, you should include them
    # if you are overwritting the settings.
    "jinja2.ext.do",
    "jinja2.ext.loopcontrols",
    "jinja2.ext.with_",
    "jinja2.ext.i18n",
    "jinja2.ext.autoescape",
    "django_jinja.builtins.extensions.CsrfExtension",
    "django_jinja.builtins.extensions.CacheExtension",
    "django_jinja.builtins.extensions.TimezoneExtension",
    "django_jinja.builtins.extensions.UrlsExtension",
    "django_jinja.builtins.extensions.StaticFilesExtension",
    "django_jinja.builtins.extensions.DjangoFiltersExtension",

    # Your extensions here...
    "path.to.your.Extension"
]
----


==== Template bytecode cache

*django-jinja* supports the Jinja2's template bytecode caching system. Including an implementation
for makes use of Django's built-in cache framework.

[source, python]
----
# Enable bytecode cache (default: False)
JINJA2_BYTECODE_CACHE_ENABLE = False

# Cache backend name for bytecode cache (default: "default")
JINJA2_BYTECODE_CACHE_NAME = "default"

# Specify custom bytecode cache subclass (default: None)
JINJA2_BYTECODE_CACHE_BACKEND = "path.to.you.cache.class"
----

link:http://jinja.pocoo.org/docs/api/#bytecode-cache[More documentation about bytecode cache]


== User Guilde (for django  +++>=+++ 1.8)

=== Introduction

Since django 1.8, multiple template engine support was added to django, and *django-jinja* comes
with support for it. Implementing the backend interface and new configuration syntax.

Django also comes with basic jinja backend, but it not has a lot of facilities and integrations
with the rest of django. *django-jinja* comes to the rescue and add everything missing.

*django-jinja* comes with that brief list of differences with django's built-in backend.

* find the templates as usual in `"<appname>/templates"` directory instead of
  `"<appname>/jinja2"` directory.
* preload template tags
* gettext message loading (i18n)
* support for django context processors

NOTE: the usage of context processors is not the recommended way anymore, and with *django-jinja*
you can done it setting global data or global constants. See below, in the django 1.8 configuration
related section.

WARNING: The settings variables used for configure django-jinja for django <= 1.7 does not works
if you are using the django 1.8 backend.


=== Quick Setup

This is a quick example of how to configure _django-jinja_ with django 1.8 configuration
formata:

[source, python]
----
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True
    },
    {
        "BACKEND": "django_jinja.backend.Jinja2",
        "APP_DIRS": True,
        "OPTIONS": {
            "match_extension", ".jinja",
        }
    },
]
----


All other options are passed directly to environment constructor.

=== Advanced options

==== Regex based template matching

Additionaly, *django-jinja* exposes, more advanced matcher, using regular exceptions:

[source, python]
----
"OPTIONS": {
    "match_regex": r"^(?!admin/).*", # this is additive to match_extension
}
----


==== Context processors support

This a helper for make possible use django's contect processors with jinja2 backend
for django 1.8. It usage is not recommended and the purpose of it existence
is for help in migration.

.Example setup a bunch of context processors:
[source, python]
----
"OPTIONS": {
    "context_processors": [
        "django.contrib.auth.context_processors.auth",
        "django.template.context_processors.debug",
        "django.template.context_processors.i18n",
        "django.template.context_processors.media",
        "django.template.context_processors.static",
        "django.template.context_processors.tz",
        "django.contrib.messages.context_processors.messages",
    ],
}
----


==== Custom filters, globals, constants and tests

django-jinja backend offers a helper options for easy setup constants, global
functions, tests and filters:

[source, python]
----
"OPTIONS": {
    "tests": {
        "mytest": "path.to.tests.mytestfn",
    },
    "filters": {
        "myfilter": "path.to.filters.myfilterfn",
    },
    "constants": {
        "hello": "hello world",
    },
    "globals": {
        "somefn": "path.to.functions.somefn",
    },
----

==== Add additional extensions

django-jinja, by default set up a great amount of extensions for make your experience
using jinja in django painless. But if you want add more extesions, you can done
using `extensions` entry on backend options:

[source, python]
----
"OPTIONS": {
    "extensions": [
        # The default extensions, you should include them
        # if you are overwritting the settings.
        "jinja2.ext.do",
        "jinja2.ext.loopcontrols",
        "jinja2.ext.with_",
        "jinja2.ext.i18n",
        "jinja2.ext.autoescape",
        "django_jinja.builtins.extensions.CsrfExtension",
        "django_jinja.builtins.extensions.CacheExtension",
        "django_jinja.builtins.extensions.TimezoneExtension",
        "django_jinja.builtins.extensions.UrlsExtension",
        "django_jinja.builtins.extensions.StaticFilesExtension",
        "django_jinja.builtins.extensions.DjangoFiltersExtension",

        # Your extensions here...
        "path.to.your.Extension"
    ]
}
----


==== Gettext Style

Jinja2 implements two stiles of gettext. You can read about it here:
http://jinja.pocoo.org/docs/dev/extensions/#newstyle-gettext.

You can switch to concrete style using the `newstyle_gettext` entry on
backend options:

[source, python]
----
"OPTIONS": {
    "newstyle_gettext": True,
}
----

==== Complete example

This is a complete configuration example with django-jinja's defaults:

[source, python]
----
TEMPLATES = [
    {
        "BACKEND": "django_jinja.backend.Jinja2",
        "APP_DIRS": True,
        "OPTIONS": {
            # Match the template names ending in .html but not the ones in the admin folder.
            "match_extension": ".html",
            "match_regex": r"^(?!admin/).*",

            "newstyle_gettext": True,
            "tests": {
                "mytest": "path.to.my.test",
            },
            "filters": {
                "myfilter": "path.to.my.filter",
            },
            "globals": {
                "myglobal": "path.to.my.globalfunc",
            },
            "constants": {
                "foo": "bar",
            },
            "extensions": [
                "jinja2.ext.do",
                "jinja2.ext.loopcontrols",
                "jinja2.ext.with_",
                "jinja2.ext.i18n",
                "jinja2.ext.autoescape",
                "django_jinja.builtins.extensions.CsrfExtension",
                "django_jinja.builtins.extensions.CacheExtension",
                "django_jinja.builtins.extensions.TimezoneExtension",
                "django_jinja.builtins.extensions.UrlsExtension",
                "django_jinja.builtins.extensions.StaticFilesExtension",
                "django_jinja.builtins.extensions.DjangoFiltersExtension",
            ],
            "autoescape": True,
            "auto_reload": settings.DEBUG,
            "translation_engine": "django.utils.translation",
        }
    },
]
----



== Differences

=== Url reversing

django-jinja comes with helpers for reverse urls. Instead of using the django's approach, it uses
a simple function called `url`.

.Reverse urls in templates
[source, html+jinja]
----
{{ url('ns:name', pk=obj.pk) }}
----

This approach is very flexible, because we do not need additional options for set a result
if executing url in one variable. With jinja2 you can use the set template tag for it:

[source, html+jinja]
----
{% set myurl=url("ns:name", pk=obj.pk) %}
----

=== Static files

Like urls, the static files can be resolved with simple `static` function available globally
in jinja context:

.Example resolving static files
[source, html+jinja]
----
{{ static("js/lib/foo.js") }}
----


=== i18n support

django-jinja inherits the jinja2 approach for handle translation strings. You can read more about
it here: http://jinja.pocoo.org/docs/dev/templates/#i18n

[source, html+jinja]
----
{{ _('Hello %(name)s', name=user.name) }}

{% trans name=user.name %}
  Hello {{ name }}
{% endtrans %}
----

Additionally, django-jinja extends the django's `makemessages` command for make it work
with jinja2 i18n tags.

If you want more django like i18n related tags, you can use extensions from https://github.com/MoritzS/jinja2-django-tags.


=== Replace jinja filters with django versions

Django and Jinja overlaps in a little subset of template filters. For handle proper this, django-jinja
gets the decistion to use the jinja versions. But if you want a django version of them, you should use
the "django_jinja.builtins.extensions.DjangoExtraFiltersExtension" extension.

The affected filters are: title, upper, lower, urlencode, urlize, wordcount, wordwrap, center
join, length, random, default, filesizeformat, pprint.


=== Registring filters in a "django" way.

django-jinja comes with facilities for loading template filters, globals and tests
from django applications.

Here an example:

[source, python]
----
# <someapp>/templatetags/<anyfile>.py
# don't forget to create __init__.py in templatetags dir

from django_jinja import library
import jinja2

@library.test(name="one")
def is_one(n):
    """
    Usage: {% if m is one %}Foo{% endif %}
    """
    return n == 1

@library.filter
def mylower(name):
    """
    Usage: {{ 'Hello'|mylower() }}
    """
    return name.lower()

@library.filter
@jinja2.contextfilter
def replace(context, value, x, y):
    """
    Filter with template context. Usage: {{ 'Hello'|replace('H','M') }}
    """
    return value.replace(x, y)


@library.global_function
def myecho(data):
    """
    Usage: {{ myecho('foo') }}
    """
    return data


@library.global_function
@library.render_with("test-render-with.jinja")
def myrenderwith(*args, **kwargs):
    """
    Render result with jinja template. Usage: {{ myrenderwith() }}
    """
    return {"name": "Foo"}
----


=== Render 4xx/500 pages with jinja

django-jinja also provides a set of views for easy
render 4xx/500 pages using jinja engine:

[source, python]
----
# yourproject/urls.py
from django_jinja import views

handler400 = views.BadRequest.as_view()
handler403 = views.PermissionDenied.as_view()
handler404 = views.PageNotFound.as_view()
handler500 = views.ServerError.as_view()
----


== Known Issues

- django-jinja does not works properly with django's `TemplateResponse` class, widely
  used by generic views. My recommendations is subclass the `TemplateResponseMixin` and
  overwrite the render_to_response function.
- Previously to django 1.8, some way of using i18n related functions are not properly
  parsed with makemessages.



== Builtin contrib modules

*django-jinja* comes with some additional contrib modules that adapts limited set of external
django apps for use it easy from jinja templates. Please note that in order to use any of these
contrib modules, you'll need to install the relevant dependent package yourself first.


[NOTE]
====
In django, creating new tags is simpler than in Jinja2. You should remember that
in jinja tags are really extensions and have a different purpose than the django template tags.

Thus for many things that the django template system uses tags, django-jinja will provide
functions with the same functionality.
====


django-pipeline
~~~~~~~~~~~~~~~

link:https://github.com/cyberdelia/django-pipeline[Pipeline] is an asset packaging
library for Django (official description).

[WARNING]
====
This plugin is deprecated, *django-pipeline* is come with good jinja support and it
should be used.

You can use the native *django-pipeline* suport for jinja using the
"pipeline.jinja2.ext.PipelineExtension" extension.
====

.Activate plugin (settings.py)
[source, python]
----
INSTALLED_APPS += ('django_jinja.contrib._pipeline',)
----

.Usage
[source, html+jinja]
----
{{ compressed_css("alias") }}
{{ compressed_js("alias") }}
----


easy-thumbnails
~~~~~~~~~~~~~~~

Easy Thumbnails is a thumbnail generation library for Django.

.Activate plugin (settings.py)
[source, python]
----
INSTALLED_APPS += ('django_jinja.contrib._easy_thumbnails',)
----

.Usage
[source, html+jinja]
----
{{ thumbnail(file, size=(400, 400)) }}
{{ user.avatar|thumbnail_url("alias") }}
----

django-subdomains
~~~~~~~~~~~~~~~~~

Subdomain helpers for the Django framework, including subdomain-based URL routing.

.Activate plugin (settings.py)
[source, python]
----
INSTALLED_APPS += ('django_jinja.contrib._subdomains',)
----

.Usage
[source, html+jinja]
----
{{ url('homepage', subdomain='wildcard') }}
----


humanize
~~~~~~~~

Django comes with humanize library that exposes some useful template filters.

.Activate plugin (settings.py)
[source, python]
----
INSTALLED_APPS += ('django_jinja.contrib._humanize',)
----

link:https://docs.djangoproject.com/en/dev/ref/contrib/humanize/[Complete list of available filters]


.[[license]]
License
-------

[source,text]
----
Copyright (c) 2011-2015 Andre Antukh <niwi@niwi.be>

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. The name of the author may not be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----
